export const mocks = {
  oportunidades: [
    { id_oportunidad: 1, titulo: 'Cotización accesorio PE para Tocancipa', empresa: 'UNION TEMPORAL BALSA 3', sector: 'Agua Potable', valor: 187000000, prob: 20, fecha: '17 Jun', avatar: 'UT', color: 2, id_estado_oportunidad: 'PROSPECTO' },
    { id_oportunidad: 2, titulo: 'Tubería 315mm PN10 para proyecto VIS', empresa: 'CMM', sector: 'Agua Potable', valor: 10000000, prob: 20, fecha: '15 Jun', avatar: 'CM', color: 4, id_estado_oportunidad: 'PROSPECTO' },
    { id_oportunidad: 3, titulo: 'Tubería PE para acueducto Ibagué', empresa: 'ACUEDUCTOS DEL TOLIMA', sector: 'Agua Potable', valor: 45000000, prob: 25, fecha: '10 Jul', avatar: 'AT', color: 1, id_estado_oportunidad: 'PROSPECTO' },
    { id_oportunidad: 4, titulo: 'Sistema riego tecnificado Pereira', empresa: 'HACIENDA VALLE VERDE', sector: 'Agro/Riego', valor: 32000000, prob: 15, fecha: '08 Jul', avatar: 'HV', color: 5, id_estado_oportunidad: 'PROSPECTO' },
    { id_oportunidad: 5, titulo: 'Oferta equipo termofusión 160mm La Dorada', empresa: 'MONTAJES JM', sector: 'Agua Potable', valor: 15000000, prob: 45, fecha: '20 Jun', avatar: 'MJ', color: 3, id_estado_oportunidad: 'CALIFICACION' },
    { id_oportunidad: 6, titulo: 'Cotización proyecto Sabanalarga', empresa: 'COL PROYECTOS', sector: 'Agua Potable', valor: 48000000, prob: 55, fecha: '18 Jun', avatar: 'CP', color: 5, id_estado_oportunidad: 'CALIFICACION' },
    { id_oportunidad: 7, titulo: 'Cotización red RCI bodega industrial', empresa: 'LOGISTICS PARK', sector: 'Industrial', valor: 68000000, prob: 45, fecha: '22 Jul', avatar: 'LP', color: 6, id_estado_oportunidad: 'CALIFICACION' },
    { id_oportunidad: 8, titulo: 'Cotización No 1393 tubería 110mm RDE 17', empresa: 'CIVILE HIDRAULICOS', sector: 'Agro/Riego', valor: 111000000, prob: 65, fecha: '25 Ago', avatar: 'CH', color: 6, id_estado_oportunidad: 'PROPUESTA' },
    { id_oportunidad: 9, titulo: 'Oferta proceso licitatorio Apartadó', empresa: 'ADOS INGENIERIA', sector: 'Agua Potable', valor: 98000000, prob: 70, fecha: '21 Abr', avatar: 'AD', color: 1, id_estado_oportunidad: 'PROPUESTA' },
    { id_oportunidad: 10, titulo: 'Oferta ampliación alcantarillado fase 2', empresa: 'AGUAS DEL MAGDALENA', sector: 'Agua Potable', valor: 54000000, prob: 75, fecha: '30 Jul', avatar: 'AM', color: 3, id_estado_oportunidad: 'PROPUESTA' },
    { id_oportunidad: 11, titulo: 'Cotización No 1248 proyecto Imola Park', empresa: 'Promotora Imola Park S.A.S', sector: 'Construcción', valor: 92000000, prob: 90, fecha: '19 Ago', avatar: 'PI', color: 4, id_estado_oportunidad: 'NEGOCIACION' },
    { id_oportunidad: 12, titulo: 'Cotización proyecto RCI Seren del Mar', empresa: 'FIRELINE', sector: 'Agua Potable', valor: 44000000, prob: 85, fecha: '26 Jun', avatar: 'FL', color: 2, id_estado_oportunidad: 'NEGOCIACION' },
    { id_oportunidad: 13, titulo: 'Oferta alcantarillado Quibdó', empresa: 'RB DE COLOMBIA SA', sector: 'Agua Potable', valor: 26000000, prob: 100, fecha: '27 Feb', avatar: 'RB', color: 3, id_estado_oportunidad: 'GANADA' },
    { id_oportunidad: 14, titulo: 'Tubería HDPE San Marcos Sucre', empresa: 'EMSERPRE', sector: 'Agua Potable', valor: 28000000, prob: 0, fecha: '06 May', avatar: 'EM', color: 5, id_estado_oportunidad: 'PERDIDA' },
  ],
  oportunidadDetalle: {
    id_oportunidad: 42,
    titulo: 'Proyecto acueducto rural - Piedecuesta',
    empresa: 'EMPAS S.A.',
    sector: 'Agua Potable',
    tipo: 'Licitación pública',
    valor: 485000000,
    valor_final: null,
    prob: 65,
    fecha_cierre: '2026-04-25',
    ciudad: 'Piedecuesta',
    id_estado_oportunidad: 'PROPUESTA',
    id_ejecutivo: 1,
    descripcion: 'Construcción de red de distribución de agua potable para zona rural de Piedecuesta, fase 1 - conducción principal 3km.',
    contacto_nombre: 'Andrés Rodríguez',
    contacto_telefono: '+57 310 555 8842',
    contacto_email: 'a.rodriguez@empas.gov.co',
    contacto_rol: 'Gerente de proyectos',
    avatar: 'AR',
    color: 2,
    edad: '13 días',
    actividades: [
      { id: 1, titulo: 'Reunión técnica en planta', fecha: 'Hoy, 10:30 AM', tipo: 'Visita', estado: 'Completada', desc: 'Visita con el ingeniero residente para revisar especificaciones del acueducto rural. Se acordó entregar propuesta revisada el 25 de marzo.' },
      { id: 2, titulo: 'Envío de cotización preliminar', fecha: '15 Mar, 3:20 PM', tipo: 'Email', estado: 'Completada', desc: 'Propuesta económica inicial por $ 485 M enviada al comité técnico.' },
      { id: 3, titulo: 'Llamada de seguimiento inicial', fecha: '10 Mar, 11:00 AM', tipo: 'Llamada', estado: 'Completada', desc: 'Primera llamada con el gerente de proyectos para conocer requerimientos técnicos.' },
    ],
    productos: [
      { id: 1, nombre: 'Tubería PE100 SDR 11 - 4"', tipo: 'Tubería', presion: '16 bar', principal: true },
      { id: 2, nombre: 'Accesorios electrofusión 4"', tipo: 'Accesorio', presion: '16 bar', principal: false },
      { id: 3, nombre: 'Válvulas de compuerta 4"', tipo: 'Válvula', presion: '16 bar', principal: false },
    ],
    historial: [
      { estado: 'PROPUESTA', fecha: '18 Mar', desc: 'Desde "Calificación" · por Juan Pérez' },
      { estado: 'CALIFICACION', fecha: '12 Mar', desc: 'Desde "Prospección" · por Juan Pérez' },
      { estado: 'PROSPECTO', fecha: '05 Mar', desc: 'Oportunidad creada' },
    ],
  },
  catalogos: {
    tipos: ['Licitación pública', 'Suministro directo', 'Proyecto a medida', 'Contrato marco'],
    sectores: ['Agua potable', 'Gas natural', 'Agricultura / Riego', 'Industria'],
    estados: ['PROSPECTO', 'CALIFICACION', 'PROPUESTA', 'NEGOCIACION', 'GANADA', 'PERDIDA'],
  },
}

export const COLUMNAS_KANBAN = [
  { id: 'PROSPECTO', label: 'Prospección', color: '#3B82F6' },
  { id: 'CALIFICACION', label: 'Calificación', color: '#F97316' },
  { id: 'PROPUESTA', label: 'Propuesta', color: '#A855F7' },
  { id: 'NEGOCIACION', label: 'Negociación', color: '#EAB308' },
  { id: 'GANADA', label: 'Ganada', color: '#22C55E' },
  { id: 'PERDIDA', label: 'Perdida', color: '#EF4444' },
]

export const ESTADO_LABELS = {
  PROSPECTO: { label: 'Prospección', badgeClass: 'prospecto' },
  CALIFICACION: { label: 'Calificación', badgeClass: 'calificacion' },
  PROPUESTA: { label: 'Propuesta', badgeClass: 'propuesta' },
  NEGOCIACION: { label: 'Negociación', badgeClass: 'negociacion' },
  GANADA: { label: 'Ganada', badgeClass: 'ganada' },
  PERDIDA: { label: 'Perdida', badgeClass: 'perdida' },
}