export const mocks = {
  leads: [
    {
      id_lead: 1,
      titulo: 'Solicitud cotización tubería para alcantarillado',
      descripcion: '',
      score: 60,
      id_estado_lead: 1,
      id_origen_lead: 5,
      nombre_empresa: 'RB DE COLOMBIA SA',
      nombre_contacto: 'Diego Castellanos',
      telefono_contacto: '+57 310 456 7890',
      email_contacto: 'dcastellanos@rbcolombia.com',
      fecha_creacion: '2026-04-29T10:00:00',
      fecha_actualizacion: '2026-04-29T10:00:00',
      id_usuario: 1,
      id_oportunidad_generada: null,
      id_motivo_descalificacion: null,
      motivo_descalificacion_obs: null,
      intereses: [{ id_interes: 1 }],
    },
    {
      id_lead: 2,
      titulo: 'Oferta tubería PE100 para proyecto VIS',
      descripcion: '',
      score: 40,
      id_estado_lead: 1,
      id_origen_lead: 5,
      nombre_empresa: 'INGEOMEGA',
      nombre_contacto: 'Diana Imbachi',
      telefono_contacto: '',
      email_contacto: '',
      fecha_creacion: '2026-04-28T10:00:00',
      fecha_actualizacion: '2026-04-28T10:00:00',
      id_usuario: 1,
      id_oportunidad_generada: null,
      id_motivo_descalificacion: null,
      motivo_descalificacion_obs: null,
      intereses: [{ id_interes: 1 }, { id_interes: 3 }],
    },
    {
      id_lead: 3,
      titulo: 'Cotización tubería 315mm PN10 para vivienda',
      descripcion: '',
      score: 60,
      id_estado_lead: 1,
      id_origen_lead: 5,
      nombre_empresa: 'GAMO INGENIEROS SAS',
      nombre_contacto: 'Andrés García',
      telefono_contacto: '',
      email_contacto: '',
      fecha_creacion: '2026-04-30T10:00:00',
      fecha_actualizacion: '2026-04-30T10:00:00',
      id_usuario: 1,
      id_oportunidad_generada: null,
      id_motivo_descalificacion: null,
      motivo_descalificacion_obs: null,
      intereses: [{ id_interes: 1 }],
    },
    {
      id_lead: 4,
      titulo: 'Cotización accesorio PE para Tocancipa',
      descripcion: '',
      score: 60,
      id_estado_lead: 2,
      id_origen_lead: 5,
      nombre_empresa: 'UNION TEMPORAL BALSA 3',
      nombre_contacto: '',
      telefono_contacto: '',
      email_contacto: '',
      fecha_creacion: '2026-04-26T10:00:00',
      fecha_actualizacion: '2026-04-26T10:00:00',
      id_usuario: 1,
      id_oportunidad_generada: null,
      id_motivo_descalificacion: null,
      motivo_descalificacion_obs: null,
      intereses: [{ id_interes: 1 }],
    },
    {
      id_lead: 5,
      titulo: 'Oferta tubería 315mm para proyecto VIS',
      descripcion: '',
      score: 40,
      id_estado_lead: 2,
      id_origen_lead: 5,
      nombre_empresa: 'GAMO INGENIEROS',
      nombre_contacto: '',
      telefono_contacto: '',
      email_contacto: '',
      fecha_creacion: '2026-04-25T10:00:00',
      fecha_actualizacion: '2026-04-25T10:00:00',
      id_usuario: 1,
      id_oportunidad_generada: null,
      id_motivo_descalificacion: null,
      motivo_descalificacion_obs: null,
      intereses: [{ id_interes: 1 }],
    },
    {
      id_lead: 6,
      titulo: 'Solicitud tubería industrial para planta',
      descripcion: '',
      score: 100,
      id_estado_lead: 3,
      id_origen_lead: 5,
      nombre_empresa: 'SOLUCIONES HIDRAULICAS',
      nombre_contacto: 'Carlos Mendoza',
      telefono_contacto: '+57 315 987 6543',
      email_contacto: 'cmendoza@solucionhidraulicas.com',
      fecha_creacion: '2026-04-25T10:00:00',
      fecha_actualizacion: '2026-04-25T10:00:00',
      id_usuario: 1,
      id_oportunidad_generada: null,
      id_motivo_descalificacion: null,
      motivo_descalificacion_obs: null,
      intereses: [{ id_interes: 1 }, { id_interes: 4 }],
    },
    {
      id_lead: 7,
      titulo: 'Cotización manifold para estación',
      descripcion: '',
      score: 80,
      id_estado_lead: 3,
      id_origen_lead: 4,
      nombre_empresa: 'INGENIERIA DEL OCCIDENTE',
      nombre_contacto: '',
      telefono_contacto: '',
      email_contacto: '',
      fecha_creacion: '2026-04-27T10:00:00',
      fecha_actualizacion: '2026-04-27T10:00:00',
      id_usuario: 1,
      id_oportunidad_generada: null,
      id_motivo_descalificacion: null,
      motivo_descalificacion_obs: null,
      intereses: [{ id_interes: 3 }],
    },
    {
      id_lead: 8,
      titulo: 'Proyecto alcantarillado EMSERPRE',
      descripcion: '',
      score: 20,
      id_estado_lead: 5,
      id_origen_lead: 4,
      nombre_empresa: 'EMSERPRE',
      nombre_contacto: '',
      telefono_contacto: '',
      email_contacto: '',
      fecha_creacion: '2026-04-15T10:00:00',
      fecha_actualizacion: '2026-04-15T10:00:00',
      id_usuario: 1,
      id_oportunidad_generada: null,
      id_motivo_descalificacion: 1,
      motivo_descalificacion_obs: 'Sin respuesta después de 3 intentos',
      intereses: [{ id_interes: 1 }, { id_interes: 3 }],
    },
    {
      id_lead: 9,
      titulo: 'Tubería HDPE para San Marcos Sucre',
      descripcion: '',
      score: 20,
      id_estado_lead: 5,
      id_origen_lead: 5,
      nombre_empresa: 'GEOCOR',
      nombre_contacto: '',
      telefono_contacto: '',
      email_contacto: '',
      fecha_creacion: '2026-04-10T10:00:00',
      fecha_actualizacion: '2026-04-10T10:00:00',
      id_usuario: 1,
      id_oportunidad_generada: null,
      id_motivo_descalificacion: 2,
      motivo_descalificacion_obs: 'Presupuesto muy bajo para el alcance',
      intereses: [{ id_interes: 1 }],
    },
  ],

  leadDetalle: {
    id_lead: 10,
    titulo: 'Cotización proyecto RCI Seren del Mar',
    descripcion: 'Cliente solicita cotización No. 20250626 para proyecto RCI en Seren del Mar, Cartagena. Enviada información técnica de sello FM.',
    score: 100,
    id_estado_lead: 3,
    id_origen_lead: 5,
    nombre_empresa: 'FIRELINE',
    nombre_contacto: 'Santiago Triana',
    telefono_contacto: '+57 317 745 9833',
    email_contacto: 'ventas@fireline.com.co',
    fecha_creacion: '2026-04-18T10:00:00',
    fecha_actualizacion: '2026-04-18T10:00:00',
    id_usuario: 1,
    id_oportunidad_generada: null,
    id_motivo_descalificacion: null,
    motivo_descalificacion_obs: null,
    intereses: [{ id_interes: 1 }, { id_interes: 3 }],
    historial: [
      { id_historial_lead: 1, id_lead: 10, id_estado_anterior: 2, id_estado_nuevo: 3, fecha_cambio: '2026-04-23T10:00:00', id_usuario: 1, comentario: 'Cliente confirmado, se encuentra en revisión de oferta' },
      { id_historial_lead: 2, id_lead: 10, id_estado_anterior: 1, id_estado_nuevo: 2, fecha_cambio: '2026-04-20T10:00:00', id_usuario: 1, comentario: 'Primera respuesta por WhatsApp, solicita información' },
      { id_historial_lead: 3, id_lead: 10, id_estado_anterior: null, id_estado_nuevo: 1, fecha_cambio: '2026-04-18T10:00:00', id_usuario: 1, comentario: 'Lead recibido por WhatsApp desde página web' },
    ],
    actividades: [
      { id: 1, titulo: 'Envío información técnica Sello FM', fecha: '2026-04-26T10:00:00', tipo: 'EMAIL', estado: 'Completada', desc: 'Se envió información técnica de sello FM y fichas técnicas' },
      { id: 2, titulo: 'Envío cotización No. 20250626', fecha: '2026-04-22T10:00:00', tipo: 'EMAIL', estado: 'Completada', desc: 'Cotización enviada para proyecto RCI en Seren del Mar, Cartagena' },
      { id: 3, titulo: 'Contacto inicial por WhatsApp', fecha: '2026-04-18T10:00:00', tipo: 'LLAMADA', estado: 'Completada', desc: 'Lead recibido desde WhatsApp, solicita cotización' },
    ],
  },

  catalogos: {
    estados: [
      { id_estado_lead: 1, nombre: 'Nuevo', tipo: 'ABIERTO', orden: 1 },
      { id_estado_lead: 2, nombre: 'Contactado', tipo: 'ABIERTO', orden: 2 },
      { id_estado_lead: 3, nombre: 'Interesado', tipo: 'CALIFICADO', orden: 3 },
      { id_estado_lead: 4, nombre: 'Calificado', tipo: 'CALIFICADO', orden: 4 },
      { id_estado_lead: 5, nombre: 'No Interesado', tipo: 'DESCALIFICADO', orden: 5 },
    ],
    origenes: [
      { id_origen_lead: 1, nombre: 'Web' },
      { id_origen_lead: 2, nombre: 'Email' },
      { id_origen_lead: 3, nombre: 'Facebook' },
      { id_origen_lead: 4, nombre: 'Instagram' },
      { id_origen_lead: 5, nombre: 'WhatsApp' },
      { id_origen_lead: 6, nombre: 'Referido' },
      { id_origen_lead: 7, nombre: 'Feria' },
    ],
    intereses: [
      { id_interes: 1, nombre: 'Tubería PE100' },
      { id_interes: 2, nombre: 'Tubería PVC' },
      { id_interes: 3, nombre: 'Accesorios PE' },
      { id_interes: 4, nombre: 'Válvulas y fittings' },
      { id_interes: 5, nombre: 'Sistema de riego' },
      { id_interes: 6, nombre: 'Equipos de termofusión' },
    ],
    motivos_descalificacion: [
      { id_motivo_descalificacion: 1, nombre: 'No responde' },
      { id_motivo_descalificacion: 2, nombre: 'Presupuesto insuficiente' },
      { id_motivo_descalificacion: 3, nombre: 'No es el responsable' },
      { id_motivo_descalificacion: 4, nombre: 'Trasladado a distribuidor' },
      { id_motivo_descalificacion: 5, nombre: 'Lead duplicado' },
    ],
    scores: [
      { value: 20, label: 'Frío', desc: 'Sin interés demostrado aún' },
      { value: 40, label: 'Tibio', desc: 'Contacto inicial, sin compromiso' },
      { value: 60, label: 'Cálido', desc: 'Interés claro, requiere seguimiento' },
      { value: 80, label: 'Caliente', desc: 'Alto potencial, oportunidad real' },
      { value: 100, label: 'Muy caliente', desc: 'Listo para conversión inmediata' },
    ],
  },
}

export const COLUMNAS_KANBAN = [
  { id: 1, label: 'Nuevo', color: '#3B82F6', tipo: 'ABIERTO' },
  { id: 2, label: 'Contactado', color: '#A855F7', tipo: 'ABIERTO' },
  { id: 3, label: 'Interesado', color: '#F39610', tipo: 'CALIFICADO' },
  { id: 5, label: 'No Interesado', color: '#EF4444', tipo: 'DESCALIFICADO' },
]